### ISSUE TITLE
Consider removing DuplicateTicketError from add_ticket

### ISSUE THREAD

**Issue by 55AAh** [OOP-opg/chessmate-rs#14]

**Comment by 55AAh** [comment]
PLEASE!!!! THIS IS EXTREMELY URGENT!!!!!!!!!!!!!!!!!!!!!!!

1. REALLY

1. REALLY @juliancoffee

**Comment by 55AAh** [comment]
![GAAhJ7v](https://user-images.githubusercontent.com/15955264/86515509-fdd4c780-be21-11ea-9477-cd48604942cc.jpg)

**Comment by juliancoffee** [comment]
solved in #17
